### ISSUE TITLE
从相册直接选择图片无法识别

### ISSUE THREAD

**Issue by mry1** [amggg/YXing#9]

**Comment by amggg** [comment]
检查Uri是否为null。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月24日(周三) 上午9:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [amggg/YXing] 从相册直接选择图片无法识别 (#9)

**Comment by mry1** [comment]
> 检查Uri是否为null。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月24日(周三) 上午9:19 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [amggg/YXing] 从相册直接选择图片无法识别 (#9) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mry1** [comment]
> > 检查Uri是否为null。
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2021年3月24日(周三) 上午9:19 收件人: _**@**_.**_>; 抄送: _**@**_.***>; 主题: [amggg/YXing] 从相册直接选择图片无法识别 (#9) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

uri是有的，跟https://github.com/yipianfengye/android-zxingLibrary这个库有一样的问题，也有很多人提了这个issue

**Comment by amggg** [comment]
我这边试是可以识别的。
你试试下面的办法:
1.二维码是否损坏（用其他软件扫码看能不能扫成功）。
2.检查Uri是否为null（有些库选择图片后 使用data.getData() 拿不到uri）
3.生成一张完好的二维码，打印出它的uri，再使用此方法识别。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月24日(周三) 上午10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amggg/YXing] 从相册直接选择图片无法识别 (#9)




   
检查Uri是否为null。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年3月24日(周三) 上午9:19 收件人: _@**._&gt;; 抄送: _@_.*&gt;; 主题: [amggg/YXing] 从相册直接选择图片无法识别 (#9) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
   
uri是有的，跟https://github.com/yipianfengye/android-zxingLibrary这个库有一样的问题，也有很多人提了这个issue

**Comment by mry1** [comment]
> 我这边试是可以识别的。 你试试下面的办法: 1.二维码是否损坏（用其他软件扫码看能不能扫成功）。 2.检查Uri是否为null（有些库选择图片后 使用data.getData() 拿不到uri） 3.生成一张完好的二维码，打印出它的uri，再使用此方法识别。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月24日(周三) 上午10:25 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [amggg/YXing] 从相册直接选择图片无法识别 (#9) 检查Uri是否为null。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年3月24日(周三) 上午9:19 收件人: _@**._&gt;; 抄送: _@_.*&gt;; 主题: [amggg/YXing] 从相册直接选择图片无法识别 (#9) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. uri是有的，跟[https://github.com/yipianfengye/android-zxingLibrary这个库有一样的问题，也有很多人提了这个issue](https://github.com/yipianfengye/android-zxingLibrary%E8%BF%99%E4%B8%AA%E5%BA%93%E6%9C%89%E4%B8%80%E6%A0%B7%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E4%B9%9F%E6%9C%89%E5%BE%88%E5%A4%9A%E4%BA%BA%E6%8F%90%E4%BA%86%E8%BF%99%E4%B8%AAissue) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你试试这张图片就知道了，https://front-xps-cdn.xsyx.xyz/2021/03/24/1795752578.jpg，保存到相册然后再识别

**Comment by amggg** [comment]
看到了。
V1.0.7 提高了识别率，可以识别了，感谢🙏



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月24日(周三) 中午11:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amggg/YXing] 从相册直接选择图片无法识别 (#9)




  
我这边试是可以识别的。 你试试下面的办法: 1.二维码是否损坏（用其他软件扫码看能不能扫成功）。 2.检查Uri是否为null（有些库选择图片后 使用data.getData() 拿不到uri） 3.生成一张完好的二维码，打印出它的uri，再使用此方法识别。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年3月24日(周三) 上午10:25 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [amggg/YXing] 从相册直接选择图片无法识别 (#9) 检查Uri是否为null。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年3月24日(周三) 上午9:19 收件人: @**.&gt;; 抄送: @.*&gt;; 主题: [amggg/YXing] 从相册直接选择图片无法识别 (#9) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. uri是有的，跟https://github.com/yipianfengye/android-zxingLibrary这个库有一样的问题，也有很多人提了这个issue — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你试试这张图片就知道了，https://front-xps-cdn.xsyx.xyz/2021/03/24/1795752578.jpg，保存到相册然后再识别

**Comment by mry1** [comment]
👍
